src/Orion/Controllers/ConferenceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Orion.ApiServices;
using Orion.Shared;

namespace Orion.Controllers;

[Authorize]
[ServiceFilter(typeof(EnsureAccessTokenFilter))]
public class ConferenceController : Controller
{
    private readonly IConferenceApiService _ApiService;

    public ConferenceController(IConferenceApiService service)
    {
        _ApiService = service;
    }

    public async Task<IActionResult> Index()
    {
        ViewBag.Title = "Organizer - Conference Overview";
        return View(await _ApiService.GetAll());
    }

    public IActionResult Add()
    {
        ViewBag.Title = "Organizer - Add Conference";
        return View(new ConferenceModel());
    }

    [HttpPost]
    public async Task<IActionResult> Add(ConferenceModel model)
    {
        if (ModelState.IsValid)
            await _ApiService.Add(model);

        return RedirectToAction("Index");
    }
}

src/Orion/Controllers/ProposalController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Orion.ApiServices;
using Orion.Shared;

namespace Orion.Controllers;

[Authorize]
[ServiceFilter(typeof(EnsureAccessTokenFilter))]
public class ProposalController : Controller
{
    private readonly IConferenceApiService _ConferenceApiService;
    private readonly IProposalApiService _ProposalApiService;

    public ProposalController(IConferenceApiService conferenceApiService, IProposalApiService proposalApiService)
    {
        _ConferenceApiService = conferenceApiService;
        _ProposalApiService = proposalApiService;
    }

    public async Task<IActionResult> Index(int conferenceId)
    {
        var conference = await _ConferenceApiService.GetById(conferenceId);
        ViewBag.Title = $"Speaker - Proposals For Conference {conference.Name} {conference.Location}";
        ViewBag.ConferenceId = conferenceId;

        return View(await _ProposalApiService.GetAll(conferenceId));
    }

    public IActionResult AddProposal(int conferenceId)
    {
        ViewBag.Title = "Speaker - Add Proposal";
        return View(new ProposalModel { ConferenceId = conferenceId });
    }

    [HttpPost]
    public async Task<IActionResult> AddProposal(ProposalModel proposal)
    {
        if (ModelState.IsValid)
            await _ProposalApiService.Add(proposal);
        return RedirectToAction("Index", new { conferenceId = proposal.ConferenceId });
    }

    public async Task<IActionResult> Approve(int proposalId)
    {
        var proposal = await _ProposalApiService.Approve(proposalId);
        return RedirectToAction("Index", new { conferenceId = proposal.ConferenceId });
    }
}

src/Orion/Views/Conference/Add.cshtml
@using Orion.Shared;
@model ConferenceModel
<form asp-action="Add">
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Name"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Name" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Location"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Location" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Start"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" type="date" asp-for="Start" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-4">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

src/Orion/Views/Conference/Index.cshtml
@using Orion.Shared;
@model IEnumerable<ConferenceModel>
<div class="row">
    <div class="col-12">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Start of event</th>
                <th>Attendees</th>
                <th>Actions</th>
            </tr>
            @foreach (var conference in Model)
            {
                <tr>
                    <td>@conference.Name</td>
                    <td>@conference.Location</td>
                    <td>@conference.Start.ToString("ddd d MMM")</td>
                    <td>@conference.AttendeeCount</td>
                    <td>
                        <a asp-controller="Proposal" asp-action="Index" asp-route-conferenceId="@conference.Id">Proposals</a>
                    </td>
                </tr>
            }
        </table>
        <a asp-action="Add">Add</a>
    </div>
</div>

@if (User.Identity != null && User.Identity.IsAuthenticated)
{
    <table class="table table-sm">
        @foreach (var claim in User.Claims)
        {
            <tr>
                <td>@claim.Type</td>
                <td>@claim.Value</td>
            </tr>
        }
    </table>
}